### ISSUE TITLE
StackOverflow onFound - android

### ISSUE THREAD

**Issue by wimvdb** [mrousavy/react-native-google-nearby-messages#16]
Hello,

I followed the setup from the example project to send a message from ios to android on 2 real devices and got a stackoverflow on the android device:

````javascript
java.lang.StackOverflowError: stack size 8MB
	at com.mrousavy.nearby.GoogleNearbyMessagesModule$connect$1.onFound(Unknown Source:2)
	at com.mrousavy.nearby.GoogleNearbyMessagesModule$connect$1.onFound(GoogleNearbyMessagesModule.kt:65)
	at com.mrousavy.nearby.GoogleNearbyMessagesModule$connect$1.onFound(GoogleNearbyMessagesModule.kt:65)
	...
````

On ios everything seems fine.

I'm using "react-native-google-nearby-messages": "^1.0.14"

The code:

````javascript
const [nearbyMessage, setNearbyMessage] = React.useState('');

    useNearbyErrorCallback(
        React.useCallback((kind, message) => {
            Alert.alert(kind, message);
        }, []),
    );

    const _connect = React.useCallback(async () => {
        console.log('Connecting...');
        await connect({
            apiKey: config.iosNearbyDeviceApiKey,
            discoveryModes: ['broadcast', 'scan'],
            discoveryMediums: ['ble'],
        });
        console.log('Connected!');
        return () => disconnect();
    }, []);
    const _publish = React.useCallback(async () => {
        const deviceName = await getDeviceName();
        console.log(`Publishing "${deviceName}"...`);
        await publish(deviceName);
        console.log(`Published "${deviceName}"!`);
    }, []);
    const _subscribe = React.useCallback(async () => {
        console.log('Subscribing...');
        await subscribe(
            (m) => {
                setNearbyMessage(m);
                console.log(`Found: ${JSON.stringify(m)}`);
            },
            (m) => {
                setNearbyMessage('');
                console.log(`Lost: ${JSON.stringify(m)}`);
            },
        );
        console.log('Subscribed!');
    }, []);
    const _checkPermissions = React.useCallback(async () => {
        const permission = await checkBluetoothPermission();
        const available = await checkBluetoothAvailability();
        Alert.alert(
            'Bluetooth Permissions:',
            `Granted: ${permission}, Available: ${available}`,
        );
    }, []);

    React.useEffect(() => {
        const start = async () => {
            try {
                await _checkPermissions();

                await _connect();
                await _subscribe();
                await _publish();
            } catch (e) {
                Alert.alert(
                    'Unknown error occured while connecting!',
                    JSON.stringify(e.message ?? e),
                );
            }
        };

        start();
        return () => disconnect();
    }, [_connect, _subscribe, _publish, _checkPermissions]);
````

**Comment by LeviWilliams** [comment]
This 100% is the same error we're dealing with over on #11 @mrousavy, this matches up with everything I've experienced on physical devices as well.
